- config_file: config/individual/conf_baseline.yaml
  name: baseline
  type: none
- config_file: config/individual/conf_full_ft_qcm_procedure1.yaml
  name: full_ft_qcm_procedure1
  type: full_ft_qcm
- config_file: config/individual/conf_full_ft_qcm_procedure2.yaml
  name: full_ft_qcm_procedure2
  type: full_ft_qcm
- config_file: config/individual/conf_full_ft_qcm_gemini.yaml
  name: full_ft_qcm_gemini
  type: full_ft_qcm
- config_file: config/individual/conf_full_ft_qcm_nova.yaml
  name: full_ft_qcm_nova
  type: full_ft_qcm
- config_file: config/individual/conf_full_ft_docvqa.yaml
  name: full_ft_docvqa
  type: full_ft_benchmark
- config_file: config/individual/conf_full_ft_ocrbench.yaml
  name: full_ft_ocrbench
  type: full_ft_benchmark
- config_file: config/individual/conf_full_ft_chartqa.yaml
  name: full_ft_chartqa
  type: full_ft_benchmark
- config_file: config/individual/conf_full_ft_sft_chosen_rej_gemini.yaml
  name: full_ft_sft_chosen_rej_gemini
  type: full_ft_chosen_rej_sft
- config_file: config/individual/conf_full_ft_sft_chosen_rej_nova.yaml
  name: full_ft_sft_chosen_rej_nova
  type: full_ft_chosen_rej_sft
- config_file: config/individual/conf_full_ft_dpo_gemini.yaml
  name: full_ft_dpo_gemini
  type: full_ft_dpo
- config_file: config/individual/conf_full_ft_dpo_nova.yaml
  name: full_ft_dpo_nova
  type: full_ft_dpo
- config_file: config/individual/conf_sft_docvqa.yaml
  name: sft_docvqa
  type: sft_benchmark
- config_file: config/individual/conf_sft_ocrbench.yaml
  name: sft_ocrbench
  type: sft_benchmark
- config_file: config/individual/conf_sft_chartqa.yaml
  name: sft_chartqa
  type: sft_benchmark
- config_file: config/individual/conf_erp_qcm_procedure1.yaml
  name: erp_qcm_procedure1
  type: sft_qcm
- config_file: config/individual/conf_erp_qcm_procedure2.yaml
  name: erp_qcm_procedure2
  type: sft_qcm
- config_file: config/individual/conf_erp_qcm_gemini.yaml
  name: erp_qcm_gemini
  type: sft_qcm
- config_file: config/individual/conf_erp_qcm_nova.yaml
  name: erp_qcm_nova
  type: sft_qcm
- config_file: config/individual/conf_erp_sft_chosen_rej_gemini.yaml
  name: erp_sft_chosen_rej_gemini
  type: sft_chosen_rej
- config_file: config/individual/conf_erp_sft_chosen_rej_nova.yaml
  name: erp_sft_chosen_rej_nova
  type: sft_chosen_rej
- config_file: config/individual/conf_dpo_docvqa.yaml
  name: dpo_docvqa
  type: dpo_benchmark
- config_file: config/individual/conf_dpo_ocrbench.yaml
  name: dpo_ocrbench
  type: dpo_benchmark
- config_file: config/individual/conf_dpo_chartqa.yaml
  name: dpo_chartqa
  type: dpo_benchmark
- config_file: config/individual/conf_erp_dpo_gemini.yaml
  name: erp_dpo_gemini
  type: dpo
- config_file: config/individual/conf_erp_dpo_nova.yaml
  name: erp_dpo_nova
  type: dpo
- config_file: config/individual/conf_full_ft_qcm_combined.yaml
  name: full_ft_qcm_combined
  type: full_ft_qcm_combined
- config_file: config/individual/conf_erp_qcm_combined.yaml
  name: erp_qcm_combined
  type: sft_qcm_combined
- config_file: config/individual/conf_erp_qcm_procedure_combined.yaml
  name: erp_qcm_procedure_combined
  type: sft_qcm_combined
- config_file: config/individual/conf_dpo_qcm_gemini.yaml
  name: dpo_qcm_gemini
  type: dpo_qcm
- config_file: config/individual/conf_dpo_qcm_nova.yaml
  name: dpo_qcm_nova
  type: dpo_qcm
- config_file: config/individual/conf_dpo_qcm_procedure1.yaml
  name: dpo_qcm_procedure1
  type: dpo_qcm
- config_file: config/individual/conf_dpo_qcm_procedure2.yaml
  name: dpo_qcm_procedure2
  type: dpo_qcm
- config_file: config/individual/conf_erp_qcm_dpo_gemini.yaml
  name: erp_qcm_dpo_gemini
  type: qcm_then_dpo
- config_file: config/individual/conf_erp_dpo_qcm_gemini.yaml
  name: erp_dpo_qcm_gemini
  type: dpo_then_qcm
- config_file: config/individual/conf_erp_dpo_qcm_nova.yaml
  name: erp_dpo_qcm_nova
  type: dpo_then_qcm
- config_file: config/individual/conf_erp_qcm_sft_chosen_rej_gemini.yaml
  name: erp_qcm_sft_chosen_rej_gemini
  type: sft_qcm_chosen_rej
- config_file: config/individual/conf_erp_qcm_sft_chosen_rej_nova.yaml
  name: erp_qcm_sft_chosen_rej_nova
  type: sft_qcm_chosen_rej
- config_file: config/individual/conf_erp_sft_chosen_rej_qcm_gemini.yaml
  name: erp_sft_chosen_rej_qcm_gemini
  type: sft_chosen_rej_qcm
- config_file: config/individual/conf_erp_sft_chosen_rej_qcm_nova.yaml
  name: erp_sft_chosen_rej_qcm_nova
  type: sft_chosen_rej_qcm
- config_file: config/individual/conf_erp_qcm_sft_chosen_rej_combined.yaml
  name: erp_qcm_sft_chosen_rej_combined
  type: sft_qcm_chosen_rej_combined
- config_file: config/individual/conf_erp_sft_chosen_rej_qcm_combined.yaml
  name: erp_sft_chosen_rej_qcm_combined
  type: sft_chosen_rej_qcm_combined
